version: 2
script:
  - npm ci
  - npx jest --ci

publish: &publish
  working_directory: ~/my-app
  docker:
    - image: circleci/node:10.4.1
  steps:
    - checkout
    
    - run:
        name: Installing dependencies
        command: npm install

    - run:
        name: Testing
        command: npm test

    - run:
        name: Login into Expo
        command: npx expo login -u 'andrealys' -p 'silveira1996'

    - run:
        name: Publish to Expo
        command: npx expo publish --non-interactive --max-workers 1 --release-channel default

jobs:
  publish_to_expo_dev:
    environment:
      EXPO_RELEASE_CHANNEL: dev
    <<: *publish

  publish_to_expo_prod:
    environment:
      EXPO_RELEASE_CHANNEL: default
    <<: *publish

workflows:
  version: 2
  my_app:
    jobs:
      - publish_to_expo_dev:
          filters:
            branches:
              only: developer
      - publish_to_expo_prod:
          filters:
            branches:
              only: master